# Generated by Django 4.2.4 on 2023-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'permissions': [('can_add_movie', 'Can add movie')],
            },
        ),
        migrations.DeleteModel(
            name='movies',
        ),
    ]
