# Generated by Django 4.2.4 on 2023-09-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_customuser_address_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_add_constumeruser', 'Can add constumeruser')]},
        ),
    ]
