# Generated by Django 4.2.4 on 2023-09-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
