# Generated by Django 4.2.4 on 2023-09-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='nombre_usuario',
        ),
    ]
