# Generated by Django 4.2.4 on 2023-09-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_rename_username_usuario_nombre_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='primer_nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='segundo_nombre',
        ),
    ]
