# Generated by Django 4.2.4 on 2023-09-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_chat_forum_delete_foro_chat_forum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
