# Generated by Django 4.2.4 on 2023-10-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_asistencia_aula_calificacion_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='materia',
            new_name='Taller',
        ),
    ]
