# Generated by Django 4.2.4 on 2023-10-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_rename_materia_calificacion_taller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='Taller',
            new_name='materia',
        ),
    ]
