# Generated by Django 4.2.4 on 2023-10-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_estudiante_user'),
    ]

    operations = [
    ]
