# Generated by Django 4.2.4 on 2023-10-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_remove_estudiante_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'permissions': [('can_add_asistencia', 'Can add asistencia')]},
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'permissions': [('can_add_aula', 'Can add aula')]},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'permissions': [('can_add_calificacion', 'Can add calificacion')]},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'permissions': [('can_add_chat', 'Can add chat')]},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'permissions': [('can_add_estudiante', 'Can add estudiante')]},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'permissions': [('can_add_forum', 'Can add forum')]},
        ),
    ]
