# Generated by Django 4.2.4 on 2023-10-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_pelicula_alter_movie_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pelicula',
        ),
    ]
