# Generated by Django 4.2.4 on 2023-10-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_delete_pelicula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.aula')),
            ],
            options={
                'permissions': [('can_add_taller', 'Can add taller')],
            },
        ),
    ]
