# Generated by Django 4.2.4 on 2023-10-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_taller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taller',
        ),
    ]
