# Generated by Django 4.2.4 on 2023-10-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0039_equipo_proyecto_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'permissions': [('can_add_archivo', 'Can add archivo')]},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'permissions': [('can_add_equipo', 'Can add equipo')]},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('can_add_Proyecto', 'Can add Proyecto')]},
        ),
    ]
